apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::872899116366:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-87CL66LW5BYH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::872899116366:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: '2022-07-25T06:37:36Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1638'
  uid: d2b0f7e4-82ae-4e66-8361-e8b0c8a72a18
